SELECT  A.TITLE
        , A.BOARD_ID
        , B.REPLY_ID
        , B.WRITER_ID
        , B.CONTENTS
        , TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
    FROM USED_GOODS_REPLY B 
    LEFT OUTER JOIN USED_GOODS_BOARD A ON A.BOARD_ID = B.BOARD_ID
        WHERE TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD') >= '2022-10-01'
          AND TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD') < '2022-11-01'
            ORDER BY B.CREATED_DATE ASC, A.TITLE ASC
