SELECT    ICE.INGREDIENT_TYPE INGREDIENT_TYPE
          , SUM(FH.TOTAL_ORDER) TOTAL_ORDER
FROM       ICECREAM_INFO ICE
LEFT JOIN   FIRST_HALF FH ON FH.FLAVOR = ICE.FLAVOR
GROUP BY   ICE.INGREDIENT_TYPE
ORDER BY   FH.TOTAL_ORDER
