SELECT  ED.ID
        , ED.GENOTYPE
        , ED2.GENOTYPE PARENT_GENOTYPE
FROM ECOLI_DATA ED
INNER JOIN ECOLI_DATA ED2 ON ED.PARENT_ID = ED2.ID
WHERE ED2.GENOTYPE & ED.GENOTYPE = ED2.GENOTYPE
ORDER BY ID
